### PR TITLE
conatcts routes and views etc

### PR DESCRIPTION
**Pull request by LesBurdock**
The crud routes for contacts done.

### CODE REVIEW

**Comment by LesBurdock** [comment]
i also touched the profiles views just to fix the formatting. I will check the conflicts when I am home later today. I assume they are nothing serious.

**Comment by LesBurdock** [comment]
Ah fuck trying to do this on my phone and clicked the wrong button to close the pull request! Will have to do this when home later.

**Comment by LesBurdock** [comment]
Ok fixed !!! GitHub for iPhone SE is quite teeny tiny! Haha

**Comment by mama-byte** [comment]
thank you for your work, Lesley!

**Pull request merged**
